packages:
  - packages/*

catalog:
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.0.13
  '@vitejs/plugin-vue': ^6.0.0
  '@vue/tsconfig': ^0.7.0
  fs-extra: ^11.3.0
  typescript: ^5.8.3
  vite: ^7.0.4
  vue: ^3.5.17
  vue-tsc: ^2.2.12
